class Hello {

  constructor(config) {
    this.target = config.target;
  }

  run() {
    this.target.innerHTML = `
      <p class="lead">
        Hello from ES2015
      </p>
      <p>
        Text is coming from a class generated by ES2015 and transpiled via babel.
      </p>
    `;
  }
}

export default Hello;

