class Hello {

    constructor(config) {
        this.target = config.target;
    }

    run() {
        this.target.innerHTML = `
      <h4 class="card-title">
        Hello from ES2015
      </h4>
      <p class="card-text">
        Text is coming from a Javascript class generated by ES2015 and transpiled via babel.
      </p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    `;
    }
}

export default Hello;